### ISSUE TITLE
博主，请问yourcookies是在CSDN的article/list里面按F12查看list的cookies嘛，我总是出错，id可以爬到，但是没有找到cookies的集合

### ISSUE THREAD

**Issue by hackerchenzhuo** [SnailMann/CAB-Tool#5]

**Comment by hackerchenzhuo** [comment]
![image](https://user-images.githubusercontent.com/42081540/70068833-b12ad300-162b-11ea-9156-44c651c91436.png)

## 就这个错误

**Comment by SnailMann** [comment]
cookies 或 name 填写错误
